In [1]:
import numpy as np

In [2]:
# 1. buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[27, 2, 7], [22, 7, 77]])
X

array([[27,  2,  7],
       [22,  7, 77]])

In [3]:
# Tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [12]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([27, 22])

In [13]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([22,  7, 77])

2. ulangi soal nomor 1 menggunakan pytorch

In [6]:
import torch

In [14]:
# buat matrix X berukuran 2x3 menggunakan pytorch
X = torch.tensor([[27, 2, 7], [22, 7, 77]])
X

tensor([[27,  2,  7],
        [22,  7, 77]])

In [15]:
# Tampilkan ukuran dari matrix X
X.shape

torch.Size([2, 3])

In [16]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:, 0]

tensor([27, 22])

In [17]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1, :]

tensor([22,  7, 77])

3. ulangi soal nomor 1 menggunakan tensorflow

In [18]:
import tensorflow as tf

In [20]:
# buat matrix X berukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[27, 2, 7], [22, 7, 77]])
X_tf


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[27,  2,  7],
       [22,  7, 77]], dtype=int32)>

In [21]:
# Tampilkan ukuran dari matrix X
tf.shape(X_tf)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [22]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([27, 22], dtype=int32)>

In [23]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([22,  7, 77], dtype=int32)>