1. buat vektor x dengan ukuran 3x1


In [ ]:
import numpy as np

In [ ]:
# 1. buat vector x dengan ukuran 3x1
x = np.array([
    [27],
    [2],
    [7]
])
x

array([[27],
       [ 2],
       [ 7]])

In [ ]:
# hitung panjang vector x
len(x)

3

In [ ]:
# tampilkan ukuran vektor
x.shape

(3, 1)

In [ ]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [ ]:
# akses elemen pertama dari vector x
x[0]

array([27])

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [ ]:
# 2. lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t


array([[27,  2,  7]])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[2, 7, 27]]) # pada soal sebelumnya atau soal no 1 vektor y belum dibuat
y                        # jadi ini saya buat dulu untuk bisa menjawab pertanyaan transpose dari y

y_t = y.T
y_t


array([[ 2],
       [ 7],
       [27]])

In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

3. Lakukan soal no 2 menggunakan pytorch dan tensorflow

In [5]:
import torch

In [7]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x = torch.tensor([
    [27],
    [2],
    [7]
])
x

x_t = x.T
x_t

tensor([[27,  2,  7]])

In [8]:
# tampilkan ukuran dari vector x_t
x_t.shape

torch.Size([1, 3])

In [10]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = torch.tensor([[2, 7, 27]]) # pada soal sebelumnya atau soal no 1 vektor y belum dibuat
y                        # jadi ini saya buat dulu untuk bisa menjawab pertanyaan transpose dari y

y_t = y.T
y_t

tensor([[ 2],
        [ 7],
        [27]])

In [11]:
# tampilkan ukuran dari vector x_t
x_t.shape

torch.Size([1, 3])